#!/usr/bin/env python
# coding: utf-8

# ## Import Libraries

# In[1]:


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates


# ## Read and View Data

# In[2]:


sp500 = pd.read_csv('SP500.csv')
sp500


# In[3]:


# Check for NaNs
sp500.isna().sum()


# In[4]:


# Check which values are NaN-- holidays
rows_with_nan = sp500[sp500.isnull().any(axis=1)]

print(rows_with_nan)


# In[5]:


# Since NaNs are on holidays, we can safely remove
sp500.dropna(inplace = True)

# Sanity check
sp500.isna().sum()


# In[6]:


# Rename date column and make sure dates are in datetime format
sp500["Date"] = pd.to_datetime(sp500["observation_date"])


# In[7]:


# Plot price over time with lines noting administration changes

# Set major ticks every 6 months
plt.figure(figsize=(12,6))
plt.plot(sp500["Date"], sp500["SP500"])

ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))

### Add lines denoting changes in presidential administration
# Trump first inauguration
plt.axvline(pd.to_datetime("2017-01-20"),
            color="red",
            linestyle="dotted",
            linewidth=2,
            label="Trump First Inauguration")

plt.legend()

# Biden inauguration
plt.axvline(pd.to_datetime("2021-01-20"),
            color="blue",
            linestyle="dotted",
            linewidth=2,
            label="Biden First Inauguration")

plt.legend()

# Trump second inauguration
plt.axvline(pd.to_datetime("2025-01-20"),
            color="red",
            linestyle="dashed",
            linewidth=2,
            label="Trump Second Inauguration")

plt.legend()

plt.xticks(rotation=45)
plt.tight_layout()
plt.title("S&P 500 Closing Price Throughout Recent Presidential Administrations")

plt.savefig('Price_over_time.png',
            dpi=300,
            bbox_inches='tight',
            pad_inches=0.25
           )
plt.show()


# ## Plot Returns to Show Volatility

# In[8]:


# Create column displaying returns by subtracting each SP500 value from the previous value
sp500["Returns"] = sp500["SP500"].diff()

# Remove NaN generated by first day (no previous day to compare it to)
sp500.dropna(inplace = True)
sp500

# Remove original date column (not in datetime format)
sp500.drop("observation_date", axis=1, inplace=True, errors='raise')
sp500


# In[9]:


# Plot volatility over time with lines noting administration changes

# Set major ticks every 6 months
plt.figure(figsize=(12,6))
plt.plot(sp500["Date"], sp500["Returns"])

ax = plt.gca()
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=6))
ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))

### Add lines denoting changes in presidential administration
# Trump first inauguration
plt.axvline(pd.to_datetime("2017-01-20"),
            color="red",
            linestyle="dotted",
            linewidth=2,
            label="Trump First Inauguration")

plt.legend()

# Biden inauguration
plt.axvline(pd.to_datetime("2021-01-20"),
            color="blue",
            linestyle="dotted",
            linewidth=2,
            label="Biden First Inauguration")

plt.legend()

# Trump second inauguration
plt.axvline(pd.to_datetime("2025-01-20"),
            color="red",
            linestyle="dashed",
            linewidth=2,
            label="Trump Second Inauguration")

plt.legend()

plt.xticks(rotation=45)
plt.ylabel("Daily Returns")
plt.tight_layout()
plt.title("S&P 500 Volatility Throughout Recent Presidential Administrations")

plt.savefig('Volatility_over_time.png',
            dpi=300,
            bbox_inches='tight',
            pad_inches=0.25
           )
plt.show()


# ## Export Preproccessed Data

# In[10]:


sp500.to_csv('sp500_clean.csv')

